Adding Bank name and amount in $ to the msg
zap-me/zap_bill_payment pull request #18
Opened 2020-09-03 05:38 UTC by eoliveros

2020-09-03 23:54 UTC, djpnewton commented
lets format the numbers to two decimal places something like like `'{0:0.2f}'.format(invoice.amount_zap/100.0)`

2020-09-07 22:42 UTC, djpnewton requested changes

2020-09-07 22:42 UTC, djpnewton commented on templates/utility.html
> +                    <input type="hidden" name="zbp_bank_name" value="{{utility.name}}"/>
this should be "zbp_utility_name" no?

2020-09-07 22:42 UTC, djpnewton commented on models.py
> +    def __init__(self, email, amount, amount_zap, bronze_broker_token, status, bank_name):
change to "utility_name"?

2020-09-07 22:42 UTC, djpnewton commented on app.py
> +def invoice_create(utility, details, email, amount, bank_name):
change bank_name to "utility_name"?

2020-09-07 22:42 UTC, djpnewton commented on app.py
> +                    msg.html = 'Invoice <a href="{}">{}</a> has updated the {} invoice with the amount of ${} to status "{}"'.format(invoice_url, invoice.token, invoice.bank_name, formatted_amount, o
change bank_name to "utility_name"?

2020-09-07 23:44 UTC, eoliveros commented on models.py
> +    def __init__(self, email, amount, amount_zap, bronze_broker_token, status, bank_name):
changed

2020-09-07 23:45 UTC, eoliveros commented on app.py
> +def invoice_create(utility, details, email, amount, bank_name):
changed.

2020-09-07 23:45 UTC, eoliveros commented on app.py
> +                    msg.html = 'Invoice <a href="{}">{}</a> has updated the {} invoice with the amount of ${} to status "{}"'.format(invoice_url, invoice.token, invoice.bank_name, formatted_amount, o
changed.

2020-09-07 23:47 UTC, eoliveros commented
pushed the commit again... test appears to be good.

will do a rebase if this is ok.

2020-09-08 02:03 UTC, merged